[uwsgi]
# Django-related settings
# python manage.py runserver
http = :8000
# 项目路径
chdir = /home/label_studio/label_studio
wsgi-file = /home/label_studio/label_studio/core/wsgi.py
# 主进程
master = true
# 指定工作进程
processes = 4
# 每个工作进程2个线程
threads = 1
# 允许在请求中开启新线程
enable-threads=true
# 指后台启动  日志输出的地方
logto = /home/label_studio/logs/uwsgi.log
log-maxsize = 102400
# 保存主进程进程号
pidfile = /home/label_studio/logs/pid_uwsgi.pid
# 虚拟环境路径
virtualenv = /home/label_studio/label_studio/venv
static-map = /static=/home/label_studio/label_studio/core/static_build
#不记录request日志，只记录错误日志
disable-logging = true

# 设置工作进程使用虚拟内存超过N MB就回收重启
reload-on-as = 1024
# 设置工作进程使用物理内存超过N MB就回收重启
reload-on-rss = 1024
# 设置工作进程每处理N个进程就会被回收重启
max-requests = 1000
# worker进程工作时长
max-worker-lifetime = 3600
# 设置平滑的重启（直到处理完接收到的请求）的长等待时间(秒)
worker-reload-mercy = 60
